import jsPDF from 'jspdf';
import {calcWeek} from './calculations';
import {money,safeFile} from './money';
export function buildDriverPdf(week,settings,broker={}){
 const doc=new jsPDF({unit:'pt',format:'letter'}), W=612,H=792; const c=calcWeek(week,settings); let y=36;
 const t=`${week.driverName||'Chauffeur'} - Semaine ${week.week||''}`; doc.setFont('helvetica','bold'); doc.setFontSize(15); doc.text(t,W/2,y,{align:'center'}); y+=22;
 doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.text(`Date de génération : ${new Date().toISOString().slice(0,10)}`,42,y); y+=16; doc.text(`Période de paie : ${week.from||''} au ${week.to||''}`,42,y); y+=24;
 doc.setFont('helvetica','bold'); doc.text(broker.company||'STATION HICK, INTELCOM',42,y); doc.text('À L’ATTENTION DE',365,y); y+=13; doc.setFont('helvetica','normal');
 doc.text(broker.address1||'9486-5482 QUÉBEC INC',42,y); doc.text(week.driverName||'',365,y); y+=13; doc.text(broker.address2||'7245-A Boul Wilfrid-Hamel',42,y); doc.text(`Code : ${week.driverCode||''}`,365,y); y+=13; doc.text(broker.city||'Québec, G2G 1B8',42,y); y+=24;
 const col=[42,170,300]; doc.setFont('helvetica','bold'); doc.text('DATES',col[0],y); doc.text('COLIS',col[1],y); doc.text('MONTANT',col[2],y); y+=10; doc.line(42,y,570,y); y+=14; doc.setFont('helvetica','normal');
 (week.dayRows||[]).forEach(d=>{doc.text(d.date||'',col[0],y); doc.text(String(d.parcels||0),col[1],y); doc.text(money(d.amount||0),col[2],y); y+=15;}); y+=10; doc.line(42,y,570,y); y+=18;
 const rows=[['Sous total Intelcom',week.totalInvoice],['Commission broker',c.commission],['Jours travaillés',String(c.workingDays)],['Mode frais',settings.feeMode==='fixedDay'?'Frais fixe par jour travaillé':'Barème par colis'],['Frais broker',c.brokerFees],['Déduction',week.deduction||0],['Avance',week.advance||0]];
 rows.forEach(r=>{doc.setFont('helvetica',r[0]==='TOTAL'?'bold':'normal');doc.text(`${r[0]} :`,42,y);doc.text(typeof r[1]==='string'?r[1]:money(r[1]),250,y);y+=15;});
 doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text('TOTAL :',42,y);doc.text(money(c.total),250,y); y+=22; doc.setFontSize(9); doc.setFont('helvetica','normal');
 doc.text(`Paiement à l’ordre de : ${broker.payTo||''}`,42,y); y+=14; doc.text(`Règlement : ${broker.paymentMethod||'Par virement bancaire'}`,42,y); y+=14; doc.text(`Email : ${broker.email||''}`,42,y); y+=14; doc.text(`Téléphone : ${broker.phone||''}`,42,y); y+=20; doc.setFont('helvetica','bold'); doc.text('MERCI DE VOTRE CONFIANCE',W/2,y,{align:'center'});
 doc.addPage(); y=42; doc.setFontSize(14); doc.setFont('helvetica','bold'); doc.text('Détails des frais broker',42,y); y+=24; doc.setFontSize(9); doc.text('Date',42,y);doc.text('Colis',135,y);doc.text('Véhicule',190,y);doc.text('Tranche',280,y);doc.text('Frais',370,y); y+=10; doc.line(42,y,570,y); y+=14; doc.setFont('helvetica','normal');
 c.feeDetails.forEach(d=>{doc.text(d.date,42,y);doc.text(String(d.parcels),135,y);doc.text(d.vehicle||'',190,y);doc.text(String(d.bracket),280,y);doc.text(money(d.fee),370,y);y+=14;}); y+=10; doc.setFont('helvetica','bold'); doc.text(`Frais broker total : ${money(c.brokerFees)}`,42,y);
 if(week.parcels?.length){const per=34,totalPages=Math.ceil(week.parcels.length/per); for(let i=0;i<totalPages;i++){doc.addPage(); y=38; doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('Détails des colis Intelcom',42,y); y+=16; doc.setFontSize(9); doc.text(`${week.driverName} ${week.driverCode}`,42,y); y+=13; doc.text(`Période : ${week.from} au ${week.to}`,42,y); doc.text(`Page détails ${i+1} / ${totalPages}`,455,y); y+=18; doc.text('Date',42,y);doc.text('Service',112,y);doc.text('Code postal',178,y);doc.text('Zone',250,y);doc.text('Tracking',315,y);doc.text('Poids',445,y);doc.text('Montant',505,y); y+=10;doc.line(42,y,570,y); y+=13; doc.setFont('helvetica','normal'); week.parcels.slice(i*per,(i+1)*per).forEach(p=>{doc.text(p.date,42,y);doc.text(p.service,112,y);doc.text(p.postal,178,y);doc.text(p.zone,250,y);doc.text(String(p.tracking).slice(0,18),315,y);doc.text(p.weight,445,y);doc.text(money(p.amount).replace(' $',' $'),505,y);y+=13;});}}
 return {doc,fileName:safeFile(`${week.driverName||'Chauffeur'} - Semaine ${week.week||''}.pdf`)};
}
